### ISSUE TITLE
执行bazel build ic_impl/ic_main的时候出现错误

### ISSUE THREAD

**Issue by lvying0019** [secretflow/interconnection-impl#10]
执行bazel build ic_impl/ic_main的时候出现如下错误，
![d9fd71e68deca634195de3bae1104ab](https://github.com/secretflow/interconnection-impl/assets/62459458/e710dfec-91c4-419c-88a1-6923c71f0c64)

**Comment by shaojian-ant** [comment]
依赖的 psi 和 spu 有冲突，稍等我更新下代码~

**Comment by shaojian-ant** [comment]
原因是 psi 依赖的 eigen库文件 的 sha256 值变了。代码已经更新。请拉取最新代码，执行 bazel clean --expunge 后重新编译

**Comment by lvying0019** [comment]
> 原因是 psi 依赖的 eigen库文件 的 sha256 值变了。代码已经更新。请拉取最新代码，执行 bazel clean --expunge 后重新编译
出现了如下新问题
![image](https://github.com/secretflow/interconnection-impl/assets/62459458/4038c05e-f7c5-45e6-9295-e5bacdeb71ff)

**Comment by shaojian-ant** [comment]
gcc 用的版本是多少？
编译要求：gcc>=11.2, cmake>=3.26, ninja, nasm>=2.15, python>=3.9, bazelisk, xxd, lld

**Comment by lvying0019** [comment]
目前是
gcc 13.2.0
cmake 3.22.1
python 3.8.18
ninja 1.10.1
nasm 2.14
我先升级不符合的版本试试

**Comment by lvying0019** [comment]
确实，这个版本就可以了
